root: true
env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:prettier/recommended"
parserOptions:
  ecmaVersion: 12
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
