# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: branch test

on:
  push:
    branches-ignore:
      - master

jobs:
  test-publish:
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dry-Run Release
        uses: ridedott/release-me-action@v3
        with:
          dry-run: true
          node-module: true
          disable-generate-changelog: true
          release-branches: '["**"]'
