# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "assets/**"
      - "tools/webpack/**"
      - "yarn.lock"
      - "tsconfig.json"
      - ".github/workflows/release.yml"

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Generate Token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.TOKEN_APP_ID }}
          private_key: ${{ secrets.TOKEN_APP_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - name: Dry-Run Release
        id: release
        uses: ridedott/release-me-action@v3
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          dry-run: true
          node-module: true
          release-rules: |
            [
              { "release": "patch", "type": "build" },
              { "release": "patch", "type": "ci" },
              { "release": "patch", "type": "chore" },
              { "release": "patch", "type": "improvement" },
              { "release": "patch", "type": "refactor" },
              { "release": false, "subject": "*\\[skip release\\]*" }
            ]
      - name: Update manifest.json version
        uses: jossef/action-set-json-field@v1
        with:
          file: dist/manifest.json
          field: version
          value: ${{ steps.release.outputs.version }}
      - name: Generate release.zip
        uses: papeloto/action-zip@v1
        with:
          files: dist/
          recursive: true
          dest: release.zip
      - name: Release
        uses: ridedott/release-me-action@v3
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          dry-run: false
          release-assets: release.zip
          node-module: true
          release-rules: |
            [
              { "release": "patch", "type": "build" },
              { "release": "patch", "type": "ci" },
              { "release": "patch", "type": "chore" },
              { "release": "patch", "type": "improvement" },
              { "release": "patch", "type": "refactor" },
              { "release": false, "subject": "*\\[skip release\\]*" }
            ]
