# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: test

on:
  pull_request:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Install
        run: yarn

  lint:
    runs-on: ubuntu-20.04
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Install
        run: yarn
      - name: Lint
        run: yarn lint
