# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: test

on:
  pull_request:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - run: yarn

  lint:
    runs-on: ubuntu-20.04
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn lint
